glab_study/accounts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^myadmin/$', views.myadmin, name='myadmin'),
    url(r'^redilect/$', views.redilect, name='redilect'),
]

glab_study/bihin/urls.py
#-----------------------------------------------------------------------
#	bihin アプリケーションのurls
#
#	2016.09.xx	V0.01	Yoshimitsu.Nakazawa
#				Djangoの勉強のために作成。
#	YYYY.MM.DD	Vx.xx	XXXX
#				XXXXXXXXXXXXXXXXXXXXXXX
#
#-----------------------------------------------------------------------
from django.conf.urls import url
#from . import views
from bihin import views


#-----------------------------------------------------------------------
#	bihinアプリケーションのurlと処理を指定
#-----------------------------------------------------------------------
urlpatterns = [
    url(r'^$', views.index, name='index'),										# /bihin		:備品一覧(Top)
    url(r'^add/$', views.bihin_edit, name='bihin_add'),							# /bihin/add	:登録
    url(r'^mod/(?P<bihin_id>\d+)/$', views.bihin_edit, name='bihin_mod'),		# /bihin/mod	:編集
]

glab_study/glab_study/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^top/', include('top.urls', namespace='top')),
    url(r'^bihin/', include('bihin.urls', namespace='bihin')),
    url(r'^login/', 'django.contrib.auth.views.login',
        {'template_name': 'accounts/login.html'}),
    url(r'^accounts/login/', 'django.contrib.auth.views.login',
        {'template_name': 'accounts/login.html'}),
    url(r'^logout/', 'django.contrib.auth.views.logout',
        {'template_name': 'accounts/logout.html'}),
    url(r'^accounts/profile/', include('top.urls', namespace='top')),
]

glab_study/top/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),                   # /top
]

glab_study/accounts/models.py
from django.db import models

# Create your models here.

glab_study/bihin/models.py
#-----------------------------------------------------------------------
#	bihin アプリケーションのmodels
#
#	2016.09.xx	V0.01	Yoshimitsu.Nakazawa
#				Djangoの勉強のために作成。
#	YYYY.MM.DD	Vx.xx	XXXX
#				XXXXXXXXXXXXXXXXXXXXXXX
#
#-----------------------------------------------------------------------
from django.db import models

# Create your models here.

PCTYPE_CHOICES = (
    (0, 'ノートパソコン'),
    (1, 'デスクトップパソコン' )
)
SHISAN_CHOICES = (
    (0, '購入品'),
    (1, 'リース' )
)
STATUS_CHOICES = (
    (0, '保管棚'),
    (1, '貸出中'),
    (2, '廃棄'),
)

#-----------------------------------------------------------------------
#	Bihin：
#   Bihin DB のモデルを定義する.
#-----------------------------------------------------------------------
class Bihin(models.Model):
    """備品"""
    bihin_no = models.CharField('管理No', max_length=255)
    bihin_type = models.IntegerField('種別', choices=PCTYPE_CHOICES)
    bihin_manufct = models.CharField('メーカー', max_length=255)
    bihin_name = models.CharField('名称', max_length=255)
    bihin_shisan = models.IntegerField('資産', choices=SHISAN_CHOICES)
    bihin_date = models.DateField('登録日')
    bihin_sts = models.IntegerField('状態', choices=STATUS_CHOICES)
    bihin_text = models.TextField('備考', null=True)

glab_study/top/models.py
from django.db import models

# Create your models here.

glab_study/bihin/forms.py
#-----------------------------------------------------------------------
#	bihin アプリケーションのform
#
#	2016.09.xx	V0.01	Yoshimitsu.Nakazawa
#				Djangoの勉強のために作成。
#	YYYY.MM.DD	Vx.xx	XXXX
#				XXXXXXXXXXXXXXXXXXXXXXX
#
#-----------------------------------------------------------------------
from django.forms import ModelForm
from bihin.models import Bihin

# Create your views here.

#-----------------------------------------------------------------------
#	BihinForm：
#   備品登録/編集にて起動される.
#   Formを作成する.
#-----------------------------------------------------------------------
class BihinForm(ModelForm):
    """備品のフォーム"""
    class Meta:
        model = Bihin
        fields = (
            'bihin_no',
            'bihin_type',
            'bihin_manufct',
            'bihin_name',
            'bihin_shisan',
            'bihin_date',
            'bihin_sts',
            'bihin_text')
#class Bihin__(models.Model):
#    bihin_no = models.CharField(max_length=100)
#    bihin_name = models.CharField(max_length=100)
#    bihin_text = models.CharField(max_length=100)
#    bihin_date = models.DateField(blank=True, null=True)
#
#class BihinForm(ModelForm):
#    class Meta:
#        model = Bihin
#        fields = ('bihin_no', 'bihin_name', 'bihin_text', 'bihin_date')

glab_study/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    contexts = {
        'user': request.user,
    }
    #return render(request, 'top/top.html', contexts)
    return HttpResponseRedirect( "top/top.html" )

glab_study/bihin/views.py
#-----------------------------------------------------------------------
#	bihin アプリケーションのviews
#
#	2016.09.xx	V0.01	Yoshimitsu.Nakazawa
#				Djangoの勉強のために作成。
#	YYYY.MM.DD	Vx.xx	XXXX
#				XXXXXXXXXXXXXXXXXXXXXXX
#
#-----------------------------------------------------------------------
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from bihin.models import Bihin
from bihin.forms import BihinForm

# Create your views here.

#-----------------------------------------------------------------------
#	index：
#   urls.py の index からここが起動される.
#   ここでは備品DBを取得し、bihin.htmlを動かす.
#-----------------------------------------------------------------------
@login_required
def index(request):
    #return HttpResponse("Bihin Top.")
    #return render(request, 'bihin/bihin.html')
    bihins = Bihin.objects.all().order_by('id')
    return render(request, 'bihin/bihin.html', {'bihins':bihins})

#-----------------------------------------------------------------------
#	index：
#   urls.py の index からここが起動される.
#   ここでは備品DBを取得し、bihin.htmlを動かす.
#-----------------------------------------------------------------------
@login_required
def bihin_edit(request, bihin_id=None):
    #return HttpResponse("Bihin Top.")
    print ( u"Debug:bihin_edit(bihin_id)", bihin_id )

    """備品の登録・編集"""
    if bihin_id:
        bihin = get_object_or_404(Bihin, pk=bihin_id)
    else:
        bihin = Bihin()

    print ( u"Debug:bihin_edit(001)" )

    if request.method == 'POST':
        form = BihinForm(request.POST, instance=bihin)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            bihin = form.save(commit=False)
            bihin.save()
            return redirect('bihin:index')
    else:    # GET の時
        form = BihinForm(instance=bihin)   # bihin インスタンスからフォームを作成
	    #return HttpResponse("Bihin Top.")

    print ( u"Debug:bihin_edit(002)" )

    d = {
        'form':form,
        #'bihin_id':bihin_id,
        #'bihin_no':bihin.bihin_no,
        #'bihin_type':bihin.bihin_type,
        #'bihin_manufct':bihin.bihin_manufct,
        #'bihin_name':bihin.bihin_name,
        #'bihin_shisan':bihin.bihin_shisan,
        #'bihin_date':bihin.bihin_date,
        #'bihin_sts':bihin.bihin_sts,
        'bihin':bihin,
    }

    #return render(request, 'bihin/bihin_edit.html', dict(form=form, bihin_id=bihin_id))
    return render(request, 'bihin/bihin_edit.html', d)

glab_study/top/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    #return HttpResponse("GLab Top.")
    return render(request, 'top/top.html')

glab_study/accounts/templates/accounts/login.html
{% extends 'base.html' %} 

{% block content %} 

  <!-- ヘッダー -->
  <div id="header">
    <div id="headtitle">GLN.Study　<small><small>- Login -</small></small></div>
  </div>

  <!-- Login -->
  <div id="form">
    <div id="formtitle">GLN.Study</div>
    <hr>

    <!--<div class="container">-->
    <form method="post" action='{% url 'django.contrib.auth.views.login' %}'>
      {% csrf_token %}
      <div class="form-item">
        <label for="id_username"><small>User ID</small></label>
        {{ form.username }}
        {{ form.username.errors }}
      </div>
      <div class="form-item">
        <label for="id_password"><small>Password</small></label>
        {{ form.password }}
        {{ form.password.errors }}  
      </div>
      <div class="button-panel">
        <input type='submit' class="button" value='login' />
        <input type='hidden' name='next' value='{{ next }}' />
      </div>
      <div class="form-footer">
      </div>
    </form>
    <!--</div>-->
  </div>

{% endblock %}

glab_study/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}

  <!-- ヘッダー -->
  <div id="header">
    <div id="headtitle">GLN.Study　<small><small>- Logout -</small></small></div>
  </div>

  <!-- コンテンツ -->
  <div id="content">
    <p>ログアウトしました</p>
    <p>再度ログインする場合は<a href="/login">こちら</a></p>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>

{% endblock %}

glab_study/accounts/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}GeekLabNagano-Study{% endblock %}</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <link href="{% static 'css/style_accounts.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
  <!-- ナビゲーション（とりあえずナビゲーションは共通） -->
  {% if user.is_authenticated %}
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/top/">GLN.Study <span style="font-size: 70%;">-勉強中-</span></a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_target">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="nav_target">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/top/">TOP</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">ツール <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/bihin/">備品管理</a></li>
                <li><a href="#">ツール</a></li>
                <li><a href="#">ツール</a></li>
              </ul>
            </li>
            <li><a href="/admin/">管理者</a></li>
            <p class="navbar-text">ようこそ {{ user.get_username }} さん.</p>
            <li><a href="/logout/">ログアウト</a></li>
          </ul>
        </div>
      </div>
    </nav>
  {% else %}
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/top/">GLN.Study <span style="font-size: 70%;">-勉強中-</span></a>
      </div>
      <div id="nav-content" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/admin/">管理者</a></li>
          <li><a href="/login/">ログイン</a></li>
        </ul>
      </div>
    </nav>
  {% endif %}

  <!-- 各コンテンツ -->
  {% block content %}
    {{ content }}
  {% endblock %}

  <!-- フッター -->
  <br>
  <div id="footer">
    <p>Copyright © 2016 日本システム技研（Team:GeekLab-Nagano） All Rights Reserved.</p>
  </div>
</body>
</html>

glab_study/bihin/templates/bihin/bihin.html
{% extends "base_head.html" %}

{% block content %}

  <!-- ヘッダー -->
  <div id="header">
    <div id="headtitle">GLN.Study　<small><small>- 備品一覧 -</small></small></div>
  </div>

  <!-- コンテナ -->
  <div id="container">

    <!-- サブメニュー -->
    <div id="submenu">
      <p>[メニュー]</p>
      <ul>
      <li><a href="{% url 'bihin:bihin_add' %}">備品登録</a></li>
      </ul>
    </div>

    <!-- コンテンツ -->
    <!--<div id="container">-->
      <div  class="container">
      <small><small>
      <div class="table-responsive">

      <!-- 以下はbihin一覧 -->
      <h4>備品一覧</h4>
      <p>※青色背景はリース品・赤色背景は廃棄したものです。</p>
      <div class="table-responsive">
      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th>#</th>
            <th>管理No.</th>
            <th>PC種別</th>
            <th>名称</th>
            <th>登録日</th>
            <th>状態</th>
            <th>使用者</th>
            <th>備考</th>
          </tr>
        </thead>
        <tbody>
          {% for bihin in bihins %}
          {% if bihin.bihin_sts = 2 %}
          <tr class="danger">
          {% else %}
          {% if bihin.bihin_shisan = 0 %}
          <tr>
          {% else %}
          <tr class="info">
          {% endif %}
          {% endif %}
            <td>{{ bihin.id }}</td>
            <td><a href="{% url 'bihin:bihin_mod' bihin_id=bihin.id %}" >{{ bihin.bihin_no }}</a></td>
            {% if bihin.bihin_type = 0 %}
            <td>ノートパソコン</td>
            {% else %}
            <td>デスクトップ</td>
            {% endif %}
            <td>{{ bihin.bihin_name }}</td>
            <td>{{ bihin.bihin_date }}</td>
            {% if bihin.bihin_sts = 0 %}
            <td> </td>
            {% else %}{% if bihin.bihin_sts = 1 %}
            <td>貸出中</td>
            {% else %}
            <td>廃棄</td>
            {% endif %}{% endif %}
            <td>{{ bihin.bihin_use }}</td>
            <td> </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      </div>
      <br>
      <br>

      <!-- 以下はサンプル -->
<!--
      <br>
      <br>
      <h4>備品一覧（以下は画面表示のサンプル. こんな感じに表示したい.）</h4>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th>#</th>
            <th>No.</th>
            <th>名称</th>
            <th>登録日</th>
            <th>状態</th>
            <th>備考</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td><a href="#">JSL.NT.120321</a></td>
            <td>ノートPC</td>
            <td>2013/06/23</td>
            <td>貸出中</td>
            <td>中沢使用中</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>JSL.NT.120322</td>
            <td>ノートPC</td>
            <td>2013/06/23</td>
            <td> </td>
            <td> </td>
          </tr>
          <tr class="danger">
            <th scope="row">3</th>
            <td class="table-danger">JSL.NT.120323</td>
            <td>ノートPC</td>
            <td>2013/06/23</td>
            <td>廃棄</td>
            <td>2016/08/10電源不良</td>
          </tr>
          <tr>
            <th scope="row">4</th>
            <td>JSL.NT.120324</td>
            <td>ノートPC</td>
            <td>2013/06/23</td>
            <td> </td>
            <td> </td>
          </tr>
          <tr>
            <th scope="row">5</th>
            <td>JSL.NT.120325</td>
            <td>ノートPC</td>
            <td>2013/06/23</td>
            <td> </td>
            <td> </td>
          </tr>
          <tr>
            <th scope="row">6</th>
            <td>JSL.NT.120326</td>
            <td>ノートPC</td>
            <td>2013/06/23</td>
            <td> </td>
            <td> </td>
          </tr>
        </tbody>
      </table>
-->
      <!-- ここまでサンプル -->

      </div>
      </small></small>
      </div>
    <!--</div>-->
  </div>

{% endblock content %}

glab_study/bihin/templates/bihin/bihin_edit.html
{% extends "base_head.html" %}
{% load bootstrap %}
{% block content %}

  <!-- ヘッダー -->
  <div id="header">
    {% if bihin_id %}
      <div id="headtitle">GLN.Study　<small><small>- 備品の修正 -</small></small></div>
    {% else %}
      <div id="headtitle">GLN.Study　<small><small>- 備品の登録 -</small></small></div>
    {% endif %}
  </div>

  <!-- コンテナ -->
  <div class="container">
  <div id="container">
    <!--<h3 class="page-header">備品の編集</h3>-->
    {% if bihin_id %}
      <form action="{% url 'bihin:bihin_mod' bihin_id=bihin_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
      <form action="{% url 'bihin:bihin_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
        {% csrf_token %}
        <div class="form-group form-group-sm">
        {{ form|bootstrap_horizontal }}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-danger btn-sm">登録</button>
            <a href="{% url 'bihin:index' %}" class="btn btn-default btn-sm">戻る</a>
          </div>
        </div>
        </div>
      </form>
  </div>
  </div>

  <!-- bootstrap で表示してみる -->
  <br><br><br>
        下のようなフォームにしたいのですが残念ながら現状は動きません。<br>
        仕方がないので、現状は上の形で動かすことにします。<br>
  <div class="container">
    <br><br>
    {% if bihin_id %}
      <form action="{% url 'bihin:bihin_mod' bihin_id=bihin_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
      <form action="{% url 'bihin:bihin_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      <form class="form-horizontal">
        <div class="form-group form-group-sm">
          <label class="control-label col-xs-2">管理No</label>
          <div class="col-xs-5">
            <input type="text" name="name" class="form-control" placeholder={{ bihin.bihin_no }}>
            <small><small><span id="helpBlock" class="help-block">ex.) JSL.NT.012345</span></small></small>
          </div>
        </div>
        <div class="form-group form-group-sm">
          <label class="control-label col-xs-2">名称</label>
          <div class="col-xs-5">
            <input type="text" name="name" class="form-control" placeholder={{ bihin.bihin_name }}>
            <small><small><span id="helpBlock" class="help-block">ex.) MacBook Pro(13inc)</span></small></small>
          </div>
        </div>
        <div class="form-group form-group-sm">
          <label class="control-label col-xs-2">登録日</label>
          <div class="col-xs-5">
            <input type="date" name="name" class="form-control" placeholder={{ bihin.bihin_date }}>
            <small><small><span id="helpBlock" class="help-block">ex.) 2016-09-03</span></small></small>
          </div>
        </div>
        <div class="form-group form-group-sm">
          <label class="control-label col-xs-2">備考</label>
          <div class="col-xs-5">
            <textarea class="form-control" rows="3"></textarea>
          </div>
        </div>
        <div class="form-group form-group-sm">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">登録</button>
          </div>
        </div>
      </form>
      </form>
  </div>
  aa

{% endblock content %}

glab_study/top/templates/base_head.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}GeekLabNagano-Study{% endblock %}</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
  <!-- ナビゲーション（とりあえずナビゲーションは共通） -->
  {% if user.is_authenticated %}
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/top/">GLN.Study <span style="font-size: 70%;">-勉強中-</span></a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_target">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="nav_target">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/top/">TOP</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">ツール <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/bihin/">備品管理</a></li>
                <li><a href="#">ツール</a></li>
                <li><a href="#">ツール</a></li>
              </ul>
            </li>
            <li><a href="/admin/">管理者</a></li>
            <p class="navbar-text">ようこそ {{ user.get_username }} さん.</p>
            <li><a href="/logout/">ログアウト</a></li>
          </ul>
        </div>
      </div>
    </nav>
  {% else %}
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/top/">GLN.Study <span style="font-size: 70%;">-勉強中-</span></a>
      </div>
      <div id="nav-content" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/admin/">管理者</a></li>
          <li><a href="/login/">ログイン</a></li>
        </ul>
      </div>
    </nav>
  {% endif %}

  <!-- 各コンテンツ -->
  {% block content %}
    {{ content }}
  {% endblock %}
  <!-- フッター -->
  <br>
  <div id="footer">
    <p>Copyright © 2016 日本システム技研（Team:GeekLab-Nagano） All Rights Reserved.</p>
  </div>
</body>
</html>

glab_study/top/templates/base_nav.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}GLab-Nagano{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="navbar-header">
    <!--ブランド名 ロゴ名の表示-->
    <a class="navbar-brand" href="#">GL.Nagano</a>
    <!--トグルボタンの設置-->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-content2">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div id="nav-content" class="collapse navbar-collapse">
    <!--リンクのリスト メニューリスト-->
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/login/">ログイン</a></li>
      <li><a href="">管理者</a></li>
      <li><a href="">お問い合わせ</a></li>
      <!--ドロップダウン化するliタグ-->
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" href="">Drop  <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Link1</a></li>
          <li><a href="#">Link2</a></li>
          <li><a href="#">Link3</a></li>
          <li class="divider"></li>
          <li><a href="#">Link A</a></li>
          <li class="divider"></li>
          <li><a href="#">LInk B</a></li>
        </ul>
      </li>
    </ul>
  </div>
  </nav>
<!--
  <div class="jumbotron">
    <div class="container">
      <h3>GeekLab.Nagano</h3>
      <p>ヘッダー部の説明を書いてもいいかも</p>
    </div>
  </div>
-->
  <div class="page-header">
    <h3>GL.Nagano</h3>
  </div>

  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>